### PR TITLE
Minor fixes for TEC

### PR DESCRIPTION
**Pull request by jdalley**
Hey all,

I've got a couple minor updates to fix some current issues with Orchil for TEC.

- Updated the URL for the Getting Started component to point at the player Wiki instead of a missing page.
- Added the missing Vote Now button for Top Mud Sites, and updated the src for the component.

I figured I'd see about getting these minor fixes in with you folks, and afterwards I'll attempt to reach out to the TEC staff about getting the latest version of Orchil deployed to client.eternalcitygame.com/tec.

Thanks!

### CODE REVIEW

**Comment by noahgibbs** [comment]
Sounds good. These are small enough changes it might be easier for them to just update their copy. But either way, these are good and we should accept them.

**Comment by jdalley** [comment]
> Sounds good. These are small enough changes it might be easier for them to just update their copy. But either way, these are good and we should accept them.

Yeah that makes sense for sure, I was also just getting a sense for whether you folks are interested in accepting PRs for things with the client in general. 

I have some other additions I've been playing around with, but they may simply be too specific to TEC. Such as a clientpref setting for `num_macro_buttons` that controls the number of macro buttons added to the right sidebar:
image

Happy to submit another PR if you think it might be acceptable, either way here's a commit with the changes: https://github.com/jdalley/orchil/commit/88c0eaef88e7ef071434915d14f94558c66e70c1

**Comment by noahgibbs** [comment]
I don't know that we want to add a setting for everybody that only shows up in the TEC client. Though I'm not sure if we have a policy on what you *should* do with client-specific settings...

**Comment by saraht45** [comment]
It would be a nice feature if individual games could have their own settings file that the base orchil code could pull from. I imagine that would take a bit of reworking though.

@jdalley are these enhancements the TEC devs  definitely want for the client?

**Comment by noahgibbs** [comment]
Sarah: not sure about the later changes, but the ones I merged were updating from the old Skotos.net URLs -- pretty clearly a good idea.

**Comment by jdalley** [comment]
> It would be a nice feature if individual games could have their own settings file that the base orchil code could pull from. I imagine that would take a bit of reworking though.
> 
> @jdalley are these enhancements the TEC devs definitely want for the client?

Like @noahgibbs said, the small fixes in this merged-pr are likely to be accepted by the devs - I've reached out to them to both let them know about this (and other recent changes from you folks like hiding both sidebars etc), and determine if they're willing to take the updates. I haven't heard back yet.

I may take a crack at the idea of giving individual games their own settings file; if I do I'll be sure to submit a PR for you to poke at and consider. I enjoy the client quite a bit as a long term TEC player, so I'm happy to contribute in any way I can.

**Comment by saraht45** [comment]
Cool :) I think it would be a nice addition to the client.

**Pull request merged**
